回退更改

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -241,27 +241,10 @@ jobs:
       #     git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
       #     echo "✅ 自定义补丁应用成功。"
 
-      - name: 应用自定义补丁patch2
-        run: |
-          echo "准备应用自定义补丁2..."
-          PATCH_FILE="${{ github.workspace }}/patchme/mypatch2.patch"
-          KERNEL_DIR="./$CONFIG/common" 
-          if [ ! -f "$PATCH_FILE" ]; then
-            echo "::error::自定义补丁文件未找到: $PATCH_FILE"
-            exit 1
-          fi
-          echo "补丁文件: $PATCH_FILE"
-          echo "目标内核目录: $KERNEL_DIR"
-          echo "-> 正在检查补丁是否能被干净应用..."
-          git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
-          echo "-> 检查通过，正在应用补丁..."
-          git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
-          echo "✅ 自定义补丁应用成功。"
-
-      # - name: 应用自定义补丁patch3
+      # - name: 应用自定义补丁patch2
       #   run: |
-      #     echo "准备应用自定义补丁3..."
-      #     PATCH_FILE="${{ github.workspace }}/patchme/mypatch3.patch"
+      #     echo "准备应用自定义补丁2..."
+      #     PATCH_FILE="${{ github.workspace }}/patchme/mypatch2.patch"
       #     KERNEL_DIR="./$CONFIG/common" 
       #     if [ ! -f "$PATCH_FILE" ]; then
       #       echo "::error::自定义补丁文件未找到: $PATCH_FILE"
@@ -274,6 +257,23 @@ jobs:
       #     echo "-> 检查通过，正在应用补丁..."
       #     git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
       #     echo "✅ 自定义补丁应用成功。"
+
+      - name: 应用自定义补丁patch3
+        run: |
+          echo "准备应用自定义补丁3..."
+          PATCH_FILE="${{ github.workspace }}/patchme/mypatch3.patch"
+          KERNEL_DIR="./$CONFIG/common" 
+          if [ ! -f "$PATCH_FILE" ]; then
+            echo "::error::自定义补丁文件未找到: $PATCH_FILE"
+            exit 1
+          fi
+          echo "补丁文件: $PATCH_FILE"
+          echo "目标内核目录: $KERNEL_DIR"
+          echo "-> 正在检查补丁是否能被干净应用..."
+          git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
+          echo "-> 检查通过，正在应用补丁..."
+          git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
+          echo "✅ 自定义补丁应用成功。"
 
       - name: 复制补丁到 block 目录
         run: |
@@ -506,7 +506,10 @@ jobs:
           CONFIG_FILE="$CONFIG/common/arch/arm64/configs/gki_defconfig"
           echo "Changing to configuration directory: $CONFIG_FILE..."
           echo "CONFIG_DEFAULT_BBR=y" >> "$CONFIG_FILE"
-          # echo "CONFIG_ZRAM_DEF_COMP_LZ4=y" >> "$CONFIG_FILE"
+          echo "CONFIG_ZRAM_DEF_COMP_LZ4=y" >> "$CONFIG_FILE"
+          sed -i 's/"drivers\/block\/zram\/zram\.ko",//g; s/"mm\/zsmalloc\.ko",//g' "$CONFIG/common/modules.bzl"
+          echo "CONFIG_MODULE_SIG_FORCE=n" >> "$CONFIG_FILE"
+          echo 'Android14_Bazel:已修复zram&zsmalloc'
           
            
       - name: 添加SUSFS配置设置
