fix 92 sublevel(patch by brokestar233)

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -223,7 +223,68 @@ jobs:
           ls -l patchblock
           echo "--- patchme ---"
           ls -l patchme
-          
+
+      - name: 修复分支sublevel 92的问题
+        run: |
+          if [ "${{ inputs.sub_level }}" = "92" ]; then
+            echo "准备应用fix1.patch..."
+            PATCH_FILE="${{ github.workspace }}/patchme/fix1.patch"
+            KERNEL_DIR="./$CONFIG/common" 
+            if [ ! -f "$PATCH_FILE" ]; then
+              echo "::error::自定义补丁文件未找到: $PATCH_FILE"
+              exit 1
+            fi
+            echo "补丁文件: $PATCH_FILE"
+            echo "目标内核目录: $KERNEL_DIR"
+            echo "-> 正在检查补丁是否能被干净应用..."
+            git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
+            echo "-> 检查通过，正在应用补丁..."
+            git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
+            echo "✅ 自定义补丁1应用成功。"
+            echo "准备应用fix2.patch..."
+            PATCH_FILE="${{ github.workspace }}/patchme/fix2.patch"
+            KERNEL_DIR="./$CONFIG/common" 
+            if [ ! -f "$PATCH_FILE" ]; then
+              echo "::error::自定义补丁文件未找到: $PATCH_FILE"
+              exit 1
+            fi
+            echo "补丁文件: $PATCH_FILE"
+            echo "目标内核目录: $KERNEL_DIR"
+            echo "-> 正在检查补丁是否能被干净应用..."
+            git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
+            echo "-> 检查通过，正在应用补丁..."
+            git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
+            echo "✅ 自定义补丁2应用成功。"
+            echo "准备应用fix3.patch..."
+            PATCH_FILE="${{ github.workspace }}/patchme/fix3.patch"
+            KERNEL_DIR="./$CONFIG/common" 
+            if [ ! -f "$PATCH_FILE" ]; then
+              echo "::error::自定义补丁文件未找到: $PATCH_FILE"
+              exit 1
+            fi
+            echo "补丁文件: $PATCH_FILE"
+            echo "目标内核目录: $KERNEL_DIR"
+            echo "-> 正在检查补丁是否能被干净应用..."
+            git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
+            echo "-> 检查通过，正在应用补丁..."
+            git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
+            echo "✅ 自定义补丁3应用成功。"
+            echo "准备应用fix4.patch..."
+            PATCH_FILE="${{ github.workspace }}/patchme/fix4.patch"
+            KERNEL_DIR="./$CONFIG/common" 
+            if [ ! -f "$PATCH_FILE" ]; then
+              echo "::error::自定义补丁文件未找到: $PATCH_FILE"
+              exit 1
+            fi
+            echo "补丁文件: $PATCH_FILE"
+            echo "目标内核目录: $KERNEL_DIR"
+            echo "-> 正在检查补丁是否能被干净应用..."
+            git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
+            echo "-> 检查通过，正在应用补丁..."
+            git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
+            echo "✅ 自定义补丁4应用成功。"
+          fi
+
       - name: 应用自定义补丁patch1fix
         run: |
           echo "准备应用自定义补丁1..."
