方案整合

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -224,44 +224,10 @@ jobs:
           echo "--- patchme ---"
           ls -l patchme
           
-      # - name: 应用自定义补丁patch1
-      #   run: |
-      #     echo "准备应用自定义补丁1..."
-      #     PATCH_FILE="${{ github.workspace }}/patchme/mypatch1.patch"
-      #     KERNEL_DIR="./$CONFIG/common" 
-      #     if [ ! -f "$PATCH_FILE" ]; then
-      #       echo "::error::自定义补丁文件未找到: $PATCH_FILE"
-      #       exit 1
-      #     fi
-      #     echo "补丁文件: $PATCH_FILE"
-      #     echo "目标内核目录: $KERNEL_DIR"
-      #     echo "-> 正在检查补丁是否能被干净应用..."
-      #     git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
-      #     echo "-> 检查通过，正在应用补丁..."
-      #     git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
-      #     echo "✅ 自定义补丁应用成功。"
-
-      # - name: 应用自定义补丁patch2
-      #   run: |
-      #     echo "准备应用自定义补丁2..."
-      #     PATCH_FILE="${{ github.workspace }}/patchme/mypatch2.patch"
-      #     KERNEL_DIR="./$CONFIG/common" 
-      #     if [ ! -f "$PATCH_FILE" ]; then
-      #       echo "::error::自定义补丁文件未找到: $PATCH_FILE"
-      #       exit 1
-      #     fi
-      #     echo "补丁文件: $PATCH_FILE"
-      #     echo "目标内核目录: $KERNEL_DIR"
-      #     echo "-> 正在检查补丁是否能被干净应用..."
-      #     git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
-      #     echo "-> 检查通过，正在应用补丁..."
-      #     git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
-      #     echo "✅ 自定义补丁应用成功。"
-
-      - name: 应用自定义补丁patch3
+      - name: 应用自定义补丁patch1fix
         run: |
-          echo "准备应用自定义补丁3..."
-          PATCH_FILE="${{ github.workspace }}/patchme/mypatch3.patch"
+          echo "准备应用自定义补丁1..."
+          PATCH_FILE="${{ github.workspace }}/patchme/mypatch1fix.patch"
           KERNEL_DIR="./$CONFIG/common" 
           if [ ! -f "$PATCH_FILE" ]; then
             echo "::error::自定义补丁文件未找到: $PATCH_FILE"
@@ -274,6 +240,40 @@ jobs:
           echo "-> 检查通过，正在应用补丁..."
           git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
           echo "✅ 自定义补丁应用成功。"
+
+      - name: 应用自定义补丁patch2
+        run: |
+          echo "准备应用自定义补丁2..."
+          PATCH_FILE="${{ github.workspace }}/patchme/mypatch2.patch"
+          KERNEL_DIR="./$CONFIG/common" 
+          if [ ! -f "$PATCH_FILE" ]; then
+            echo "::error::自定义补丁文件未找到: $PATCH_FILE"
+            exit 1
+          fi
+          echo "补丁文件: $PATCH_FILE"
+          echo "目标内核目录: $KERNEL_DIR"
+          echo "-> 正在检查补丁是否能被干净应用..."
+          git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
+          echo "-> 检查通过，正在应用补丁..."
+          git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
+          echo "✅ 自定义补丁应用成功。"
+
+      # - name: 应用自定义补丁patch3
+      #   run: |
+      #     echo "准备应用自定义补丁3..."
+      #     PATCH_FILE="${{ github.workspace }}/patchme/mypatch3.patch"
+      #     KERNEL_DIR="./$CONFIG/common" 
+      #     if [ ! -f "$PATCH_FILE" ]; then
+      #       echo "::error::自定义补丁文件未找到: $PATCH_FILE"
+      #       exit 1
+      #     fi
+      #     echo "补丁文件: $PATCH_FILE"
+      #     echo "目标内核目录: $KERNEL_DIR"
+      #     echo "-> 正在检查补丁是否能被干净应用..."
+      #     git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
+      #     echo "-> 检查通过，正在应用补丁..."
+      #     git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
+      #     echo "✅ 自定义补丁应用成功。"
 
       - name: 复制补丁到 block 目录
         run: |
@@ -459,7 +459,7 @@ jobs:
           set -e
           echo "写入LZ4KD&ZSTDN config依赖"
           CONFIG_FILE="$CONFIG/common/arch/arm64/configs/gki_defconfig"
-
+          echo "CONFIG_DEFAULT_BBR=y" >> "$CONFIG_FILE"
           if [ "${{ inputs.kernel_version }}" = "5.10" ]; then
             echo "CONFIG_ZSMALLOC=y" >> "$CONFIG_FILE"
             echo "CONFIG_ZRAM=y" >> "$CONFIG_FILE"
@@ -501,15 +501,15 @@ jobs:
             echo "CONFIG_ZRAM_WRITEBACK=y" >> "$CONFIG_FILE"
           fi
 
-      - name: 设置全部特性
+      - name: 设置lz4全部特性
+        if: ${{ !inputs.use_zram }}
         run: |
           CONFIG_FILE="$CONFIG/common/arch/arm64/configs/gki_defconfig"
           echo "Changing to configuration directory: $CONFIG_FILE..."
           echo "CONFIG_DEFAULT_BBR=y" >> "$CONFIG_FILE"
+          echo "CONFIG_CRYPTO_LZ4=y" >> "$CONFIG_FILE"
           echo "CONFIG_ZRAM_DEF_COMP_LZ4=y" >> "$CONFIG_FILE"
-          sed -i 's/"drivers\/block\/zram\/zram\.ko",//g; s/"mm\/zsmalloc\.ko",//g' "$CONFIG/common/modules.bzl"
-          echo "CONFIG_MODULE_SIG_FORCE=n" >> "$CONFIG_FILE"
-          echo 'Android14_Bazel:已修复zram&zsmalloc'
+          echo "CONFIG_ZRAM_WRITEBACK=y" >> "$CONFIG_FILE"
           
            
       - name: 添加SUSFS配置设置
