test patch fit

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -316,6 +316,23 @@ jobs:
             echo "✅ 自定义补丁4应用成功。"
           fi
 
+      - name: 应用自定义补丁test1
+        run: |
+          echo "准备应用自定义补丁1..."
+          PATCH_FILE="${{ github.workspace }}/patchme/test.patch"
+          KERNEL_DIR="./$CONFIG/common" 
+          if [ ! -f "$PATCH_FILE" ]; then
+            echo "::error::自定义补丁文件未找到: $PATCH_FILE"
+            exit 1
+          fi
+          echo "补丁文件: $PATCH_FILE"
+          echo "目标内核目录: $KERNEL_DIR"
+          echo "-> 正在检查补丁是否能被干净应用..."
+          git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
+          echo "-> 检查通过，正在应用补丁..."
+          git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
+          echo "✅ 自定义补丁应用成功。"
+      
       - name: 应用自定义补丁patch1fix
         run: |
           echo "准备应用自定义补丁1..."
@@ -627,6 +644,11 @@ jobs:
           echo "更改为配置目录: $CONFIG..."
           cd "$CONFIG"
           echo "Adding configuration settings to gki_defconfig..."
+
+          #测试patchopen
+
+          echo "CONFIG_DELAYED_SYSFS_WRITER=y" >> ./common/arch/arm64/configs/gki_defconfig
+
 
           # Add KSU configuration settings
           echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
