update gki-kernel.yaml

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -315,23 +315,6 @@ jobs:
             git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
             echo "✅ 自定义补丁4应用成功。"
           fi
-
-      # - name: 应用自定义补丁test1
-      #   run: |
-      #     echo "准备应用自定义补丁1..."
-      #     PATCH_FILE="${{ github.workspace }}/patchme/test.patch"
-      #     KERNEL_DIR="./$CONFIG/common" 
-      #     if [ ! -f "$PATCH_FILE" ]; then
-      #       echo "::error::自定义补丁文件未找到: $PATCH_FILE"
-      #       exit 1
-      #     fi
-      #     echo "补丁文件: $PATCH_FILE"
-      #     echo "目标内核目录: $KERNEL_DIR"
-      #     echo "-> 正在检查补丁是否能被干净应用..."
-      #     git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
-      #     echo "-> 检查通过，正在应用补丁..."
-      #     git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
-      #     echo "✅ 自定义补丁应用成功。"
       
       - name: 应用自定义补丁patch1fix
         run: |
@@ -388,6 +371,23 @@ jobs:
         run: |
           echo "准备应用@brokestar233修改的zswap"
           PATCH_FILE="${{ github.workspace }}/patchme/zswap.patch"
+          KERNEL_DIR="./$CONFIG/common" 
+          if [ ! -f "$PATCH_FILE" ]; then
+            echo "::error::自定义补丁文件未找到: $PATCH_FILE"
+            exit 1
+          fi
+          echo "补丁文件: $PATCH_FILE"
+          echo "目标内核目录: $KERNEL_DIR"
+          echo "-> 正在检查补丁是否能被干净应用..."
+          git -C "$KERNEL_DIR" apply --check "$PATCH_FILE"
+          echo "-> 检查通过，正在应用补丁..."
+          git -C "$KERNEL_DIR" apply --verbose "$PATCH_FILE"
+          echo "✅ 自定义补丁应用成功。"
+          
+      - name: 应用自定义补丁test2
+        run: |
+          echo "准备应用自定义补丁2..."
+          PATCH_FILE="${{ github.workspace }}/patchme/test2.patch"
           KERNEL_DIR="./$CONFIG/common" 
           if [ ! -f "$PATCH_FILE" ]; then
             echo "::error::自定义补丁文件未找到: $PATCH_FILE"
